---
- name: Create ServiceNow Ticket
  hosts: localhost
  gather_facts: false

  vars:
    short_description: "New IT issue from auto-responder"
    description: "This ticket was auto-created based on an email support request."

  tasks:
    - name: Create ticket in ServiceNow
      uri:
        url: "{{ service_now_instance  }}/api/now/table/{{ SNOW_API_TABLE }}"
        method: POST
        user: "{{ service_now_username }}"
        password: "{{ service_now_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body:
          short_description: "{{ short_description }}"
          description: "{{ description }}"
          urgency: "2"
          impact: "2"
        status_code: 201
        return_content: yes
      register: snow_response

    - name: Output created ticket number
      debug:
        msg: "Created ServiceNow ticket number: {{ snow_response.json.result.number }}"
